ptz:
  description: Pan and tilt camera.
  fields:
    entity_id:
      description: "Name of the entity to rotate"
      example: "tapo_control.living_room"
    tilt: 
      description: "Tilt direction. Allowed values: UP, DOWN"
      example: "UP"
    pan: 
      description: "Pan direction. Allowed values: RIGHT, LEFT"
      example: "RIGHT"
    preset:
      description: "PTZ preset ID, starts at 1"
      example: "1"
    distance:
      description: "Distance coefficient. Sets how much PTZ should be executed in one request. Allowed values: floating point numbers, 0 to 1"
      example: "0.1"