ptz:
  description: Pan and tilt camera
  fields:
    entity_id:
      description: "Entity to adjust"
      example: "tapo_control.living_room"
    tilt: 
      description: "Tilt direction. Allowed values: UP, DOWN"
      example: "UP"
    pan: 
      description: "Pan direction. Allowed values: RIGHT, LEFT"
      example: "RIGHT"
    preset:
      description: "PTZ preset ID, starts at 1"
      example: "1"
    distance:
      description: "Distance coefficient. Sets how much PTZ should be executed in one request. Allowed values: floating point numbers, 0 to 1"
      example: "0.1"
set_privacy_mode:
  description: Sets privacy mode
  fields:
    entity_id:
      description: "Entity to set privacy mode for"
      example: "tapo_control.living_room"
    privacy_mode: 
      description: "Sets privacy mode for camera. Possible values: on, off"
      example: "on"
set_alarm_mode:
  description: Sets alarm mode
  fields:
    entity_id:
      description: "Entity to set alarm mode for"
      example: "tapo_control.living_room"
    alarm_mode: 
      description: "Sets alarm mode for camera. Possible values: on, off"
      example: "on"
    sound: 
      description: "Sets whether the alarm should use sound on motion detected. Possible values: on, off"
      example: "on"
    light: 
      description: "Sets whether the alarm should use light on motion detected. Possible values: on, off"
      example: "on"
set_led_mode:
  description: Sets LED mode
  fields:
    entity_id:
      description: "Entity to set LED mode for"
      example: "tapo_control.living_room"
    led_mode: 
      description: "Sets LED mode for camera. Possible values: on, off"
      example: "on"
set_motion_detection_mode:
  description: Sets motion detection mode
  fields:
    entity_id:
      description: "Entity to set motion detection mode for"
      example: "tapo_control.living_room"
    motion_detection_mode: 
      description: "Sets motion detection mode for camera. Possible values: high, normal, low, off"
      example: "normal"
set_auto_track_mode:
  description: "Sets auto track mode. 
  
  WARNING: This mode is not available in Tapo app and we do not know why. Use at your own risk and please report any success or failures in GitHub."
  fields:
    entity_id:
      description: "Entity to set auto track mode for"
      example: "tapo_control.living_room"
    auto_track_mode: 
      description: "Sets auto track mode for camera. Possible values: on, off"
      example: "on"
reboot:
  description: Reboots the camera
  fields:
    entity_id:
      description: "Entity to reboot"
      example: "tapo_control.living_room"